### ISSUE TITLE
ResponseClientsGetClientDetailDetail.detail.vlanId should be of type *int

### ISSUE THREAD

**Issue by olivier-leduc** [cisco-en-programmability/dnacenter-go-sdk#45]
**Prerequisites**
* [yes] Have you tested the operation in the API directly?
* [4.0.11 ] Do you have the latest SDK version?
* [yes ] Review [compability matrix](https://github.com/cisco-en-programmability/dnacenter-go-sdk/tree/main#compatibility-matrix)

**Describe the bug**
ResponseClientsGetClientDetailDetail.detail.vlanId should be of type *int

**Expected behavior**
this type error shouldn't be thrown at compile time
Pull request #44 

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.
invalid operation: cannot indirect details.VLANID (variable of type string)
json: cannot unmarshal number into Go struct field ResponseClientsGetClientDetailDetail.detail.vlanId of type string 

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.3.4-72142
* Go Version: go1.19.2
* SDK version: 4.0.11 
* OS Version: CentOS 8

**Additional context**

**Comment by olivier-leduc** [comment]
#44

**Comment by fmunozmiranda** [comment]
Hi @olivier-leduc, thanks for report, please try it again with [v4.014](https://pkg.go.dev/github.com/cisco-en-programmability/dnacenter-go-sdk/v4@v4.0.14).
